trigger:
- none


parameters:
- name: reponame
  displayName: Reponame
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

variables:
- name: reponame
  value: ${{ parameters.reponame }}

resources:
  repositories:
    - repository: Reponame
      type: git
      name: ${{ parameters.reponame }}
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
