trigger:
- none


parameters:
- name: reponame
  displayName: Reponame
  type: string
  default: SaradaJagarlamudi/FunctionApp-Python-Sample
  values:
  - SaradaJagarlamudi/FunctionApp-Python-Sample
  - SaradaJagarlamudi/Test
  - SaradaJagarlamudi/SaradaJagarlamudi



jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.reponame }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.reponame }}
